### ISSUE TITLE
Readme build instructions use the incorrect directory

### ISSUE THREAD

**Issue by ScottWales** [executablebooks/cookiecutter-jupyter-book#31]
**Describe the bug**

The readme file's build instructions say

```
(Recommended) Remove the existing {{ cookiecutter.book_name }}/_build/ directory
Run jupyter-book build {{ cookiecutter.book_name }}/
```

however the directory is actually named `{{cookiecutter.book_slug}}`.

**To Reproduce**

Create a book where the book name and slug are different and follow the build instructions in the generated readme

**Expected behavior**

Readme should read

```
(Recommended) Remove the existing {{ cookiecutter.book_slug }}/_build/ directory
Run jupyter-book build {{ cookiecutter.book_slug }}/
```

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.6
- Package versions or output of `jupyter-book --version`:
```
Jupyter Book: 0.10.1
MyST-NB: 0.12.0
Sphinx Book Theme: 0.0.41
MyST-Parser: 0.13.5
Jupyter-Cache: 0.4.2
NbClient: 0.5.2
```
- Operating System: WSL

**Additional context**

**Comment by TomasBeuzen** [comment]
Thanks for this @ScottWales - I'll make a PR later tonight to fix this one up. Appreciate it!
