### ISSUE TITLE
Link broken for image used to demonstrate inclusion of images

### ISSUE THREAD

**Issue by ttimbers** [executablebooks/cookiecutter-jupyter-book#36]
### Describe the problem

The image at  linked to in `{{cookiecutter.book_slug}}/{{cookiecutter.book_slug}}/notebooks.ipynb` (https://myst-parser.readthedocs.io/en/latest/_static/logo.png) no longer exists:

<img width="481" alt="Screen Shot 2021-11-22 at 2 41 25 PM" src="https://user-images.githubusercontent.com/6865016/142945802-4bbe136c-8359-4624-9c86-d586cf69cd21.png">

A new image should be linked to there.

### Steps to reproduce

It exists locally, and in the example on the web (https://executablebooks.github.io/cookiecutter-jupyter-book/notebooks.html).

**Comment by TomasBeuzen** [comment]
Thanks @ttimbers! Should be fixed now by #37
