### ISSUE TITLE
Provide Creative Commons Licenses as an option

### ISSUE THREAD

**Issue by yuvipanda** [executablebooks/cookiecutter-jupyter-book#39]
### Context

The current cookiecutter mostly presents *code* options for the license, rather than more conventional *document* licenses. Primarily, the various creative commons licenses!

### Proposal

Add a couple of common CC licenses - at least CC BY and CC BY-SA. Perhaps at the cost of removing some of the existing licenses (I'd suggest GPL (which is equivalent IMO to CC BY-SA), and perhaps ISC)

**Comment by TomasBeuzen** [comment]
Great idea - all done @yuvipanda :)

- Added CC BY and CC BY-SA licenses to cookiecutter options
- Removed GPL and ISC options
- Updated template files, using [most recent files from the Jupyter Book repo](https://github.com/executablebooks/jupyter-book/tree/master/jupyter_book/book_template)

**Comment by yuvipanda** [comment]
Thanks a lot, @TomasBeuzen!
