### ISSUE TITLE
Replace `peaceiris/actions-gh-pages` with `actions/deploy-pages` Workflow

### ISSUE THREAD

**Issue by michaelweinold** [executablebooks/cookiecutter-jupyter-book#41]
### Context

The documentation of the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/blob/main/README.md) workflow now links to the official GitHub Actions [deploy-pages](https://github.com/actions/deploy-pages) workflow:

> **Note**
>
> See also the GitHub official GitHub Pages Action first.
>
> - [GitHub Pages now uses Actions by default | The GitHub Blog](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/)
> - [GitHub Pages: Custom GitHub Actions Workflows (beta) | GitHub Changelog](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/)

Could this be used instead?

### Proposal

Replace `actions-gh-pages` with `deploy-pages`.

### Tasks and updates

- [ ] check if `deploy-pages` would allow for publishing the `jupyter-book` site
- [ ] update the [`cookiecutter-jupyter-book/.github/workflows/deploy.yml`](https://github.com/executablebooks/cookiecutter-jupyter-book/blob/main/.github/workflows/deploy.yml) file

**Comment by agoose77** [comment]
Thanks @michaelweinold! The latest PR by @kolibril13 in #42 should have addressed this :)
